public class DemoSobjectDml {
    public static void DemoDml(){
       /* //list to store the account records inserted by dml
        list<Account> accList = new List<Account>();
        //new instance is required to insert a record
        Account acc1 = new account();
        Account acc2 = new account();
        //editing field to insert
        acc1.Name = 'Test Account Dml 1';
        acc2.Name = 'Test Account Dml 2';
        acc1.Phone = '90909';
        acc2.Phone = '23232';
        //adding to list
        accList.add(acc1);
        accList.add(acc2);
        insert accList;
        system.debug('Account Id--->'+acc1.id);
        system.debug('Account Id 2--->'+acc2.id);*/
    }
}